# Custom Language File for Launcher Customizer

[ejs.app]
title = "Colibri Launcher"

[ejs.landing]
mediaLinkURL = "https://labcolibri.com/"
mediaGitHubURL = "https://github.com/labcolibri/ColibriLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/labcolibri/ColibriLauncher"
supportLink = "https://github.com/labcolibri/ColibriLauncher/issues"

[ejs.welcome]
welcomeHeader = "Colibri Lab"
welcomeDescription = "자요로운 개발 Colibri Lab"
welcomeDescCTA = "Colibri Lab은 개발한 모든 프로그램을 무료로 배포하고 있습니다"